spring.application.name=Loja-de-pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/estudos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
